# Generated by Django 6.1.1 on 2026-09-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('what', models.JSONField(blank=True, default=list)),
                ('who', models.JSONField(blank=True, default=list)),
                ('when', models.JSONField(blank=True, default=list)),
                ('where', models.JSONField(blank=True, default=list)),
                ('why', models.JSONField(blank=True, default=list)),
                ('how', models.JSONField(blank=True, default=list)),
                ('how_much', models.JSONField(blank=True, default=list)),
                ('original_text', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
    ]
