# Generated by Django 6.1.1 on 2026-09-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Label bebas, mis. '9router - rli-cloude'", max_length=255)),
                ('purpose', models.CharField(choices=[('chat', 'Chat / Generation'), ('embedding', 'Embedding')], max_length=20)),
                ('base_url', models.CharField(help_text='Endpoint OpenAI-compatible, mis. http://localhost:11434/v1', max_length=255)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('model_name', models.CharField(help_text="Nama model yang dikirim ke API, mis. 'llama3.2:3b'", max_length=255)),
                ('dim', models.IntegerField(blank=True, help_text='Dimensi vektor — khusus purpose=embedding', null=True)),
                ('is_active', models.BooleanField(default=False, help_text='Model yang sedang dipakai app untuk purpose ini')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
