# Generated by Django 6.1.1 on 2026-09-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0002_aimodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='RebuildProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('done', 'Done')], default='idle', max_length=20)),
                ('total', models.IntegerField(default=0)),
                ('processed', models.IntegerField(default=0)),
                ('success', models.IntegerField(default=0)),
                ('failed_ids', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
