# Generated by Django 6.1.1 on 2026-09-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0003_rebuildprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='rebuildprogress',
            name='base_url',
            field=models.CharField(blank=True, help_text='Base URL embedding yang dipakai run ini', max_length=255),
        ),
        migrations.AddField(
            model_name='rebuildprogress',
            name='dim',
            field=models.IntegerField(blank=True, help_text='REPORT_EMBEDDING_DIM yang dipakai run ini', null=True),
        ),
        migrations.AddField(
            model_name='rebuildprogress',
            name='model_name',
            field=models.CharField(blank=True, help_text='EMBEDDING_MODEL yang dipakai run ini', max_length=255),
        ),
    ]
